spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg-321f1ffe-folko85-48e2.aivencloud.com:24161/defaultdb?sslmode=require
    username: ENC(SjI7Dxp9C1W0nBW43bWLhNvc1tjwr2y9)
    password: ENC(ThqMVopWFkNAjirs7W7nbp5K9DtXHLz/zkoNNNj8iCM=)
  liquibase:
    change-log: /db/changelog/changelog.yml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    bean: encryptorBean