spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:chat.db
  liquibase:
    change-log: /db/changelog/changelog.yml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.intech.chat.config.sqlite.SQLiteDialect
    generate-ddl: true
    show-sql: false

jasypt:
  encryptor:
    bean: encryptorBean